### ISSUE TITLE
error: PlatformException(Courier Android SDK Error, null: null, g2.c: null: null

### ISSUE THREAD

**Issue by CesarArellano** [trycourier/courier-flutter#12]
Hello there, I have this issue only in Android release mode and execute this Courier.shared.signIn(accessToken: courierAuthKey, userId: userId) method  in my Flutter App

<img width="1423" alt="image" src="https://github.com/trycourier/courier-flutter/assets/38898501/1578d502-a517-46e9-8029-bc535ab5d0ee">

**Comment by CesarArellano** [comment]
In Android debug mode and iOS (release & debug) work the push notifications.

**Comment by mikemilla** [comment]
@charlesverge @CesarArellano low level SDKs have been updated. Take a look at the latest version `2.1.0`. This issue should be resolved.
