### ISSUE TITLE
Push notification rendered but didn't sent to Mobile App, (APNs)

### ISSUE THREAD

**Issue by MuhammadHaxeeb** [trycourier/courier-flutter#13]
Hey, 

we are facing issues while working with courier flutter, The issue we are facing while sending notifications from the backend to our device and it didn’t go through. It just shows an error at the encountered step. Please see the image below

<img width="954" alt="4e41204e-e37c-42e3-8966-0336ff0361d3" src="https://github.com/trycourier/courier-flutter/assets/109177674/df7e76b2-2e02-4213-b1c5-3c5a0ed0ce16">

And the Code we used to push the notification.

`{
  "channel": {
    "taxonomy": "push:apn"
  },
  "configuration": "5bb0****-3f41-43f0-a4**8-396a****7a7e8",
  "provider": "apn",
  "willRetry": false,
  "errorMessage": "[{\"device\":\"9d50f4fcb77f1475d18acfb********9bb32f2943258cd571c494de6de1fde9\",\"status\":400,\"response\":{\"reason\":\"BadDeviceToken\"}}]"
}`

**Meanwhile, the response we see on the Flutter terminal while running the code**

`📡 New Courier API Request

URL: https://api.courier.com/users/8b3dac37-21a6-4051-a8bf-501782d9b35c/tokens/9d50f4fcb77f1475d18acfb7c3ce37389bb32f2943258cd571c494de6de1fde9

Method: PUT

Body: {"device":{"model":"iPhone","device_id":"B946EB38-****-4E7D-****-753018D28FCF","app_id":"com.fin****rs.glo***ency","manufacturer":"apple","platform":"ios"},"provider_key":"apn"}

Status: 204`

When we switch the keys from Prouction to Dev env everything working fine and we are recieving the notifications as well. But the moment we switch from Dev env to Prod env it didn’t go through from the backend side. Please let us know how to fix this issue.

**Comment by mikemilla** [comment]
@MuhammadHaxeeb you are experiencing sending a push notification to Apple's production environment using a dev (aka sandbox) token. This will result in "BadDeviceToken"

Here is how to fix this:

1. Click "Settings" in Courier and change your environment to Production
2. In your APNS configuration (https://app.courier.com/integrations/catalog/apn) make sure it is set to use "Production". Make sure your test configuration is not using Production.
3. In your app, when you use a JWT to "sign in", make sure you are using the same environment on your backend as you are in your app. Testing locally will likely use Courier Test, App Store / Testflight will use Courier Production (https://app.courier.com/settings/api-keys)

**Comment by MuhammadHaxeeb** [comment]
Thanks for the response, Let us look into the provided solution and we will get back if we need any more info from you.

Thanks & Regards


[Logo]<https://finjineers.com/>

Muhammad Haseeb
CEO

finjineers.com/<http://finjineers.com/>

[facebook icon]<https://www.facebook.com/finjineers> [twitter icon] <https://twitter.com/finjineers>  [youtube icon] <https://www.youtube.com/channel/UCjtz5mBzFas0ica8g7NdNhw>  [linkedin icon] <https://www.linkedin.com/company/finjineers/>  [instagram icon] <https://www.instagram.com/finjineers/>  [pinterest icon] <https://www.pinterest.com/finjineers/>

E: ***@***.******@***.***>
M: +92 311 4226828
T: +92 311 4226828
A: 2nd Floor Safia Center, Hall Road, Lahore, Punjab, Pakistan, 54000

From: Mike Miller ***@***.***>
Date: Friday, March 29, 2024 at 1:39 AM
To: trycourier/courier-flutter ***@***.***>
Cc: MuhammadHaxeeb ***@***.***>, Mention ***@***.***>
Subject: Re: [trycourier/courier-flutter] Push notification rendered but didn't sent to Mobile App, (APNs) (Issue #13)


@MuhammadHaxeeb<https://github.com/MuhammadHaxeeb> you are experiencing sending a push notification to Apple's production environment using a dev (aka sandbox) token. This will result in "BadDeviceToken"

Here is how to fix this:

  1.  Click "Settings" in Courier and change your environment to Production
  2.  In your APNS configuration (https://app.courier.com/integrations/catalog/apn) make sure it is set to use "Production". Make sure your test configuration is not using Production.
  3.  In your app, when you use a JWT to "sign in", make sure you are using the same environment on your backend as you are in your app. Testing locally will likely use Courier Test, App Store / Testflight will use Courier Production (https://app.courier.com/settings/api-keys)

**Comment by MuhammadHaxeeb** [comment]
According to documentation while setting up the Android app with Courier,

we somehow facing an integration issue regarding Step 5 according to the Android setup docs
 https://github.com/trycourier/courier-flutter/blob/master/Docs/PushNotifications.md#:~:text=Change%20your%20MainActivity%20to%20extend%20the%20CourierFlutterActivity.

Since the courier_flutter plugin required MainAcitivty to extend the CourierFlutterActivity class in MainActivity.
But we are using another plugin local_auth for Biometric, And the local_auth plugin requires the MainActivity should be extended from FlutterFragmentActivity(),

What we should do in this situation.?


From: Muhammad Haseeb ***@***.***>
Date: Friday, March 29, 2024 at 2:17 AM
To: trycourier/courier-flutter ***@***.***>, trycourier/courier-flutter ***@***.***>
Cc: Mention ***@***.***>, Ivan Stasiuk ***@***.***>, Olatunji Oyebanji ***@***.***>
Subject: Re: [trycourier/courier-flutter] Push notification rendered but didn't sent to Mobile App, (APNs) (Issue #13)

Thanks for the response, Let us look into the provided solution and we will get back if we need any more info from you.

Thanks & Regards


[Logo]<https://finjineers.com/>

Muhammad Haseeb
CEO

finjineers.com/<http://finjineers.com/>

[facebook icon]<https://www.facebook.com/finjineers> [twitter icon] <https://twitter.com/finjineers>  [youtube icon] <https://www.youtube.com/channel/UCjtz5mBzFas0ica8g7NdNhw>  [linkedin icon] <https://www.linkedin.com/company/finjineers/>  [instagram icon] <https://www.instagram.com/finjineers/>  [pinterest icon] <https://www.pinterest.com/finjineers/>

E: ***@***.******@***.***>
M: +92 311 4226828
T: +92 311 4226828
A: 2nd Floor Safia Center, Hall Road, Lahore, Punjab, Pakistan, 54000

From: Mike Miller ***@***.***>
Date: Friday, March 29, 2024 at 1:39 AM
To: trycourier/courier-flutter ***@***.***>
Cc: MuhammadHaxeeb ***@***.***>, Mention ***@***.***>
Subject: Re: [trycourier/courier-flutter] Push notification rendered but didn't sent to Mobile App, (APNs) (Issue #13)


@MuhammadHaxeeb<https://github.com/MuhammadHaxeeb> you are experiencing sending a push notification to Apple's production environment using a dev (aka sandbox) token. This will result in "BadDeviceToken"

Here is how to fix this:

  1.  Click "Settings" in Courier and change your environment to Production
  2.  In your APNS configuration (https://app.courier.com/integrations/catalog/apn) make sure it is set to use "Production". Make sure your test configuration is not using Production.
  3.  In your app, when you use a JWT to "sign in", make sure you are using the same environment on your backend as you are in your app. Testing locally will likely use Courier Test, App Store / Testflight will use Courier Production (https://app.courier.com/settings/api-keys)

**Comment by mikemilla** [comment]
This was resolved via Intercom. Closing this issue out.
