### ISSUE TITLE
extend the CourierFlutterActivity class in MainActivity

### ISSUE THREAD

**Issue by Finjineersdev** [trycourier/courier-flutter#14]
According to documentation while setting up the Android app with Courier,

we somehow facing an integration issue regarding Step 5 according to the Android setup docs
 https://github.com/trycourier/courier-flutter/blob/master/Docs/PushNotifications.md#:~:text=Change%20your%20MainActivity%20to%20extend%20the%20CourierFlutterActivity.

Since the courier_flutter plugin required MainAcitivty to extend the CourierFlutterActivity class in MainActivity.
But we are using another plugin local_auth for Biometric, And the local_auth plugin requires the MainActivity should be extended from FlutterFragmentActivity(),

What we should do in this situation.? We are already in Production, An earlier response would be really appreciated.

<img width="1155" alt="image" src="https://github.com/trycourier/courier-flutter/assets/167119127/db93208a-4062-460f-8069-6661656ccc9a">

**Comment by mikemilla** [comment]
All good. Working on a fix this week. Will let you know when it's live @Finjineersdev

**Comment by mikemilla** [comment]
@Finjineersdev you can use `CourierFlutterFragmentActivity` to achieve this. Try this:

```
class MainActivity: CourierFlutterFragmentActivity() {
  ...
}
```

If you're still having trouble let me know.
