### ISSUE TITLE
Archive / Delete Notifications from courier inbox

### ISSUE THREAD

**Issue by Finjineersdev** [trycourier/courier-flutter#15]
Hey, 

We are using Courier notification service for our project and we used the Flutter framework for the mobile app, our business requirement includes letting our customers achieve/Delete their inbox notifications, but somehow this plugin doesn’t provide any way to do this, we would like to request you if you can help us to implement this feature with or without this plugin, we are already in production and we would appreciate your earlier response. Thank you!

**Comment by mikemilla** [comment]
@Finjineersdev we've started development internally on archiving. Still in progress, just giving an update!

**Comment by mikemilla** [comment]
@Finjineersdev archiving is now supported in the SDK! 🙌

Checkout version `3.0`+

Here are some relevant snippets.

```
final client = Courier.shared.client;
await client.inbox.archive(messageId: "your_message_id");
final res = await client.inbox.getArchivedMessages();
```

**Comment by Finjineersdev** [comment]
That's good news, Thank you so much 									Muhammad ***@***.***: +92 311 4226828T: +92 311 4226828A: 2nd Floor Safia Center, Hall Road, Lahore, Punjab, Pakistan, 54000								From:  Mike Miller ***@***.***>Date:  Wednesday, August 14, 2024 at 10:52 PMTo:  trycourier/courier-flutter ***@***.***>Cc:  Finjineersdev ***@***.***>, Mention ***@***.***>Subject:  Re: [trycourier/courier-flutter] Archive / Delete Notifications from courier inbox (Issue #15)
@Finjineersdev archiving is now supported in the SDK! 🙌
Checkout version 3.0+
Here are some relevant snippets.
final client = Courier.shared.client;
await client.inbox.archive(messageId: "your_message_id");
final res = await client.inbox.getArchivedMessages();
