### ISSUE TITLE
Error creating a Notification Service

### ISSUE THREAD

**Issue by adityathakurxd** [trycourier/courier-flutter#9]
I was following along with this [tutorial](https://www.youtube.com/live/1Pb-4p1ZAPY?feature=share) on setting up Courier in Flutter. Although I am getting an error with the Notification Service.

```bash
e: file:///Users/adityathakur/Desktop/firsthelp/android/app/src/main/kotlin/com/aditya/firsthelp/FirstNotificationService.kt:22:29 Unresolved reference: MainActivity

FAILURE: Build failed with an exception.
```

I noticed the project on live stream was created with Kotlin for Android enabled. But, my project structure for android is different. The `MainActivity` is in the `kotlin` folder (image attached) while it is inside the `java` folder on the live stream. Should I instead create my `NotificationService` inside the `java` folder?

<img width="977" alt="Screenshot 2023-02-18 at 5 23 59 PM" src="https://user-images.githubusercontent.com/53579386/219864531-037f111c-f7f5-43b7-a360-6322f44878be.png">

**Comment by mikemilla** [comment]
Yes, place your files into the java folder and try again please. @adityathakurxd 

Sorry for the delayed response as well!

**Comment by mikemilla** [comment]
@adityathakurxd if you are still experiencing issues, please leave a comment here and I can help you out.
